const PARSE_APP_ID = process.env.PARSE_APP_ID;
const PARSE_JAVASCRIPT_KEY = process.env.PARSE_JAVASCRIPT_KEY;
const MASTER_KEY = process.env.MASTER_KEY;

module.exports = {
  PARSE_APP_ID: "gRUFeqZIKNLqLv2Y13MspeZIujPyjsrA2OMyOQDh",
  PARSE_JAVASCRIPT_KEY: "8h6xf5FJjTVLImExxVOIP23p2CLOCxKW7V93cBPn",
  MASTER_KEY: "9w31NJO9WYecVSqakBJjbc541oDp85Rdit5UAINE",
};